export const Colors = {
  // Light Theme
  light: {
    background: '#F4F4F4',
    tint: '#FF4C4C',
    tabIconDefault: '#687076',
    tabIconSelected: '#FF4C4C',
    white: '#fff',
    black: '#333',
    darkGrey: '#666',
    lightGrey: '#999',
    softText: '#555',
    cardBackground: '#fff',
    borderColor: '#E0E0E0',
    shadowColor: '#000',
  },
  // Dark Theme
  dark: {
    background: '#121212',
    tint: '#FF6B6B',
    tabIconDefault: '#9CA3AF',
    tabIconSelected: '#FF6B6B',
    white: '#1F1F1F',
    black: '#FFFFFF',
    darkGrey: '#9CA3AF',
    lightGrey: '#6B7280',
    softText: '#D1D5DB',
    cardBackground: '#1F1F1F',
    borderColor: '#374151',
    shadowColor: '#000',
  },
  // Common colors
  background: '#F4F4F4',
  tint: '#FF4C4C',
  tabIconDefault: '#687076',
  tabIconSelected: '#FF4C4C',
  white: '#fff',
  black: '#333',
  darkGrey: '#666',
  lightGrey: '#999',
  softText: '#555',
};
